### ISSUE TITLE
npm install command fails on react version constraint

### ISSUE THREAD

**Issue by Nfinished** [vadimdemedes/create-pastel-app#7]
```
  ✖ Install dependencies
    → npm ERR!     /home/nfinished/.npm/_logs/2021-05-14T02_32_39_212Z-debug.log
    Build application
    Link executable
Error: Command failed: npm install pastel ink react prop-types
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR!
npm ERR! While resolving: new-project@0.0.0
npm ERR! Found: react@17.0.2
npm ERR! node_modules/react
npm ERR!   react@"*" from the root project
npm ERR!   peer react@">=16.8.0" from ink@2.7.1
npm ERR!   node_modules/ink
npm ERR!     ink@"*" from the root project
npm ERR!     peer ink@"^2.1.1" from pastel@1.1.1
npm ERR!     node_modules/pastel
npm ERR!       pastel@"*" from the root project
npm ERR!
npm ERR! Could not resolve dependency:
npm ERR! peer react@"^16.8.6" from pastel@1.1.1
npm ERR! node_modules/pastel
npm ERR!   pastel@"*" from the root project
npm ERR!
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
npm ERR!
npm ERR! See /home/nfinished/.npm/eresolve-report.txt for a full report.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/nfinished/.npm/_logs/2021-05-14T02_32_39_212Z-debug.log


    at makeError (/home/nfinished/.npm/_npx/385ce523a0690f92/node_modules/execa/index.js:174:9)
    at /home/nfinished/.npm/_npx/385ce523a0690f92/node_modules/execa/index.js:278:16
    at processTicksAndRejections (node:internal/process/task_queues:94:5)
    ```

**Comment by Nfinished** [comment]
My mistake, this is an issue with [vadimdemedes/pastel](https://github.com/vadimdemedes/pastel)
