### ISSUE TITLE
optionally exclude link stage

### ISSUE THREAD

**Issue by olegtaranenko** [vadimdemedes/create-pastel-app#9]
because of linking executable to /opt/local/bin, I need to use sudo npx create-pastel-app.
Which causes error afterthere

```
Mac-Pro:projects user1$ sudo npx create-pastel-app ts-app
Password:

  ✔ Copy files
  ✔ Install dependencies
  ✔ Format code
  ✔ Build
  ✔ Link executable
  
  Pastel app created in ts-app:
    $ cd ts-app
  
  Build:
    $ npm run build
  
  Watch and rebuild:
    $ npm run dev
  
  Run:
    $ ts-app

Mac-Pro:projects user1$ cd ts-app/

Mac-Pro:ts-app user1$ npm run test

> ts-app@0.0.0 test
> prettier --check . && xo && ava

Checking formatting...
All matched files use Prettier code style!

(node:97472) ExperimentalWarning: Custom ESM Loaders is an experimental feature and might change at any time
(Use `node --trace-warnings ...` to show where the warning was created)
  Uncaught exception in test.tsx

  TypeError [ERR_UNKNOWN_FILE_EXTENSION]: Unknown file extension ".tsx" for /Users/user1/dev/currinex/projects/ts-app/test.tsx

  ✘ test.tsx exited with a non-zero exit code: 1
  ✘ Internal error
  Error: EACCES: permission denied, mkdir '/Users/user1/dev/currinex/projects/ts-app/node_modules/.cache/ava'
  Error: EACCES: permission denied, mkdir '/Users/user1/dev/currinex/projects/ts-app/node_modules/.cache/ava'
      at Object.mkdirSync (node:fs:1403:3)
      at Api._createCacheDir (file:///Users/user1/dev/currinex/projects/ts-app/node_modules/ava/lib/api.js:338:6)
      at Api.run (file:///Users/user1/dev/currinex/projects/ts-app/node_modules/ava/lib/api.js:309:96)
      at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
      at async loadCli (file:///Users/user1/dev/currinex/projects/ts-app/node_modules/ava/lib/cli.js:501:21)


  ─

  1 uncaught exception

```

**Comment by vadimdemedes** [comment]
It's an issue with your local setup, which has Node.js installed in a system folder. If you use a version manager like n or nvm, Node.js will be installed in a home folder and won't require a sudo.
